services:
  mongo:
    image: mongo:7.0.2
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/autovist --quiet
  app:
    build: .
    environment:
      - MONGO_URL=mongodb://mongo/autovist
    depends_on:
      mongo:
        condition: service_healthy
  nginx:
    image: nginx:1.25.2-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
